### ISSUE TITLE
Fix RTD build failure

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stginga#121]
RTD has been failing for over a week. Traceback below. @eteq , do you happen to know why, since you wrote this part?

```python
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/stginga/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/stginga/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 189, in __init__
    self._init_builder(self.buildername)
  File "/home/docs/checkouts/readthedocs.org/user_builds/stginga/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 252, in _init_builder
    self.emit('builder-inited')
  File "/home/docs/checkouts/readthedocs.org/user_builds/stginga/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 508, in emit
    results.append(callback(self, *args))
  File "conf.py", line 187, in notebooks_to_rst
    from IPython.nbconvert.nbconvertapp import NbConvertApp
ImportError: No module named IPython.nbconvert.nbconvertapp

Exception occurred:
  File "conf.py", line 187, in notebooks_to_rst
    from IPython.nbconvert.nbconvertapp import NbConvertApp
ImportError: No module named IPython.nbconvert.nbconvertapp
```

**Comment by pllim** [comment]
Turns out to be some extra dependency required by `nbconvert` now. Fixed in 1ed91177fb4c96fbf205931dc7c682c6afcebb30.
